/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import java.time.LocalDateTime;

import org.cardanofoundation.rosetta.api.jooq.tables.AddressUtxo;
import org.jooq.JSONB;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AddressUtxoRecord extends UpdatableRecordImpl<AddressUtxoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.address_utxo.tx_hash</code>.
     */
    public void setTxHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.address_utxo.tx_hash</code>.
     */
    public String getTxHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.address_utxo.output_index</code>.
     */
    public void setOutputIndex(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.address_utxo.output_index</code>.
     */
    public Short getOutputIndex() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.address_utxo.slot</code>.
     */
    public void setSlot(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.address_utxo.slot</code>.
     */
    public Long getSlot() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.address_utxo.block_hash</code>.
     */
    public void setBlockHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.address_utxo.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.address_utxo.epoch</code>.
     */
    public void setEpoch(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.address_utxo.epoch</code>.
     */
    public Integer getEpoch() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.address_utxo.lovelace_amount</code>.
     */
    public void setLovelaceAmount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.address_utxo.lovelace_amount</code>.
     */
    public Long getLovelaceAmount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.address_utxo.amounts</code>.
     */
    public void setAmounts(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.address_utxo.amounts</code>.
     */
    public JSONB getAmounts() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.address_utxo.data_hash</code>.
     */
    public void setDataHash(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.address_utxo.data_hash</code>.
     */
    public String getDataHash() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.address_utxo.inline_datum</code>.
     */
    public void setInlineDatum(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.address_utxo.inline_datum</code>.
     */
    public String getInlineDatum() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.address_utxo.owner_addr</code>.
     */
    public void setOwnerAddr(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.address_utxo.owner_addr</code>.
     */
    public String getOwnerAddr() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.address_utxo.owner_addr_full</code>.
     */
    public void setOwnerAddrFull(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.address_utxo.owner_addr_full</code>.
     */
    public String getOwnerAddrFull() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.address_utxo.owner_stake_addr</code>.
     */
    public void setOwnerStakeAddr(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.address_utxo.owner_stake_addr</code>.
     */
    public String getOwnerStakeAddr() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.address_utxo.owner_payment_credential</code>.
     */
    public void setOwnerPaymentCredential(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.address_utxo.owner_payment_credential</code>.
     */
    public String getOwnerPaymentCredential() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.address_utxo.owner_stake_credential</code>.
     */
    public void setOwnerStakeCredential(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.address_utxo.owner_stake_credential</code>.
     */
    public String getOwnerStakeCredential() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.address_utxo.script_ref</code>.
     */
    public void setScriptRef(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.address_utxo.script_ref</code>.
     */
    public String getScriptRef() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.address_utxo.reference_script_hash</code>.
     */
    public void setReferenceScriptHash(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.address_utxo.reference_script_hash</code>.
     */
    public String getReferenceScriptHash() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.address_utxo.is_collateral_return</code>.
     */
    public void setIsCollateralReturn(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.address_utxo.is_collateral_return</code>.
     */
    public Boolean getIsCollateralReturn() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>public.address_utxo.block</code>.
     */
    public void setBlock(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.address_utxo.block</code>.
     */
    public Long getBlock() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.address_utxo.block_time</code>.
     */
    public void setBlockTime(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.address_utxo.block_time</code>.
     */
    public Long getBlockTime() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.address_utxo.update_datetime</code>.
     */
    public void setUpdateDatetime(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.address_utxo.update_datetime</code>.
     */
    public LocalDateTime getUpdateDatetime() {
        return (LocalDateTime) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Short, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressUtxoRecord
     */
    public AddressUtxoRecord() {
        super(AddressUtxo.ADDRESS_UTXO);
    }

    /**
     * Create a detached, initialised AddressUtxoRecord
     */
    public AddressUtxoRecord(String txHash, Short outputIndex, Long slot, String blockHash, Integer epoch, Long lovelaceAmount, JSONB amounts, String dataHash, String inlineDatum, String ownerAddr, String ownerAddrFull, String ownerStakeAddr, String ownerPaymentCredential, String ownerStakeCredential, String scriptRef, String referenceScriptHash, Boolean isCollateralReturn, Long block, Long blockTime, LocalDateTime updateDatetime) {
        super(AddressUtxo.ADDRESS_UTXO);

        setTxHash(txHash);
        setOutputIndex(outputIndex);
        setSlot(slot);
        setBlockHash(blockHash);
        setEpoch(epoch);
        setLovelaceAmount(lovelaceAmount);
        setAmounts(amounts);
        setDataHash(dataHash);
        setInlineDatum(inlineDatum);
        setOwnerAddr(ownerAddr);
        setOwnerAddrFull(ownerAddrFull);
        setOwnerStakeAddr(ownerStakeAddr);
        setOwnerPaymentCredential(ownerPaymentCredential);
        setOwnerStakeCredential(ownerStakeCredential);
        setScriptRef(scriptRef);
        setReferenceScriptHash(referenceScriptHash);
        setIsCollateralReturn(isCollateralReturn);
        setBlock(block);
        setBlockTime(blockTime);
        setUpdateDatetime(updateDatetime);
        resetChangedOnNotNull();
    }
}
