/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import java.time.LocalDateTime;

import org.cardanofoundation.rosetta.api.jooq.tables.Address;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>preprod.address.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>preprod.address.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>preprod.address.address</code>.
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>preprod.address.address</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>preprod.address.addr_full</code>.
     */
    public void setAddrFull(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>preprod.address.addr_full</code>.
     */
    public String getAddrFull() {
        return (String) get(2);
    }

    /**
     * Setter for <code>preprod.address.payment_credential</code>.
     */
    public void setPaymentCredential(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>preprod.address.payment_credential</code>.
     */
    public String getPaymentCredential() {
        return (String) get(3);
    }

    /**
     * Setter for <code>preprod.address.stake_address</code>.
     */
    public void setStakeAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>preprod.address.stake_address</code>.
     */
    public String getStakeAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>preprod.address.stake_credential</code>.
     */
    public void setStakeCredential(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>preprod.address.stake_credential</code>.
     */
    public String getStakeCredential() {
        return (String) get(5);
    }

    /**
     * Setter for <code>preprod.address.update_datetime</code>.
     */
    public void setUpdateDatetime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>preprod.address.update_datetime</code>.
     */
    public LocalDateTime getUpdateDatetime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Long id, String address, String addrFull, String paymentCredential, String stakeAddress, String stakeCredential, LocalDateTime updateDatetime) {
        super(Address.ADDRESS);

        setId(id);
        setAddress(address);
        setAddrFull(addrFull);
        setPaymentCredential(paymentCredential);
        setStakeAddress(stakeAddress);
        setStakeCredential(stakeCredential);
        setUpdateDatetime(updateDatetime);
        resetChangedOnNotNull();
    }
}
