/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import java.time.LocalDateTime;

import org.cardanofoundation.rosetta.api.jooq.tables.CostModel;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CostModelRecord extends UpdatableRecordImpl<CostModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>preprod.cost_model.hash</code>.
     */
    public void setHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>preprod.cost_model.hash</code>.
     */
    public String getHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>preprod.cost_model.costs</code>.
     */
    public void setCosts(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>preprod.cost_model.costs</code>.
     */
    public JSONB getCosts() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>preprod.cost_model.slot</code>.
     */
    public void setSlot(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>preprod.cost_model.slot</code>.
     */
    public Long getSlot() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>preprod.cost_model.block</code>.
     */
    public void setBlock(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>preprod.cost_model.block</code>.
     */
    public Long getBlock() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>preprod.cost_model.block_time</code>.
     */
    public void setBlockTime(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>preprod.cost_model.block_time</code>.
     */
    public Long getBlockTime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>preprod.cost_model.update_datetime</code>.
     */
    public void setUpdateDatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>preprod.cost_model.update_datetime</code>.
     */
    public LocalDateTime getUpdateDatetime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CostModelRecord
     */
    public CostModelRecord() {
        super(CostModel.COST_MODEL);
    }

    /**
     * Create a detached, initialised CostModelRecord
     */
    public CostModelRecord(String hash, JSONB costs, Long slot, Long block, Long blockTime, LocalDateTime updateDatetime) {
        super(CostModel.COST_MODEL);

        setHash(hash);
        setCosts(costs);
        setSlot(slot);
        setBlock(block);
        setBlockTime(blockTime);
        setUpdateDatetime(updateDatetime);
        resetChangedOnNotNull();
    }
}
