/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import java.time.LocalDateTime;

import org.cardanofoundation.rosetta.api.jooq.tables.Delegation;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DelegationRecord extends UpdatableRecordImpl<DelegationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>preprod.delegation.tx_hash</code>.
     */
    public void setTxHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>preprod.delegation.tx_hash</code>.
     */
    public String getTxHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>preprod.delegation.cert_index</code>.
     */
    public void setCertIndex(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>preprod.delegation.cert_index</code>.
     */
    public Integer getCertIndex() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>preprod.delegation.credential</code>.
     */
    public void setCredential(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>preprod.delegation.credential</code>.
     */
    public String getCredential() {
        return (String) get(2);
    }

    /**
     * Setter for <code>preprod.delegation.pool_id</code>.
     */
    public void setPoolId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>preprod.delegation.pool_id</code>.
     */
    public String getPoolId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>preprod.delegation.address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>preprod.delegation.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>preprod.delegation.epoch</code>.
     */
    public void setEpoch(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>preprod.delegation.epoch</code>.
     */
    public Integer getEpoch() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>preprod.delegation.slot</code>.
     */
    public void setSlot(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>preprod.delegation.slot</code>.
     */
    public Long getSlot() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>preprod.delegation.block_hash</code>.
     */
    public void setBlockHash(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>preprod.delegation.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(7);
    }

    /**
     * Setter for <code>preprod.delegation.block</code>.
     */
    public void setBlock(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>preprod.delegation.block</code>.
     */
    public Long getBlock() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>preprod.delegation.block_time</code>.
     */
    public void setBlockTime(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>preprod.delegation.block_time</code>.
     */
    public Long getBlockTime() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>preprod.delegation.update_datetime</code>.
     */
    public void setUpdateDatetime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>preprod.delegation.update_datetime</code>.
     */
    public LocalDateTime getUpdateDatetime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DelegationRecord
     */
    public DelegationRecord() {
        super(Delegation.DELEGATION);
    }

    /**
     * Create a detached, initialised DelegationRecord
     */
    public DelegationRecord(String txHash, Integer certIndex, String credential, String poolId, String address, Integer epoch, Long slot, String blockHash, Long block, Long blockTime, LocalDateTime updateDatetime) {
        super(Delegation.DELEGATION);

        setTxHash(txHash);
        setCertIndex(certIndex);
        setCredential(credential);
        setPoolId(poolId);
        setAddress(address);
        setEpoch(epoch);
        setSlot(slot);
        setBlockHash(blockHash);
        setBlock(block);
        setBlockTime(blockTime);
        setUpdateDatetime(updateDatetime);
        resetChangedOnNotNull();
    }
}
