/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import java.time.LocalDateTime;

import org.cardanofoundation.rosetta.api.jooq.tables.ErrorReview;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ErrorReviewRecord extends UpdatableRecordImpl<ErrorReviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>preprod.error_review.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>preprod.error_review.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>preprod.error_review.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>preprod.error_review.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>preprod.error_review.comment</code>.
     */
    public void setComment(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>preprod.error_review.comment</code>.
     */
    public String getComment() {
        return (String) get(2);
    }

    /**
     * Setter for <code>preprod.error_review.checked_by</code>.
     */
    public void setCheckedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>preprod.error_review.checked_by</code>.
     */
    public String getCheckedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>preprod.error_review.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>preprod.error_review.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ErrorReviewRecord
     */
    public ErrorReviewRecord() {
        super(ErrorReview.ERROR_REVIEW);
    }

    /**
     * Create a detached, initialised ErrorReviewRecord
     */
    public ErrorReviewRecord(Integer id, String status, String comment, String checkedBy, LocalDateTime lastUpdated) {
        super(ErrorReview.ERROR_REVIEW);

        setId(id);
        setStatus(status);
        setComment(comment);
        setCheckedBy(checkedBy);
        setLastUpdated(lastUpdated);
        resetChangedOnNotNull();
    }
}
