/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import java.time.LocalDateTime;

import org.cardanofoundation.rosetta.api.jooq.tables.Error;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ErrorRecord extends UpdatableRecordImpl<ErrorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>preprod.error.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>preprod.error.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>preprod.error.block</code>.
     */
    public void setBlock(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>preprod.error.block</code>.
     */
    public Long getBlock() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>preprod.error.error_code</code>.
     */
    public void setErrorCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>preprod.error.error_code</code>.
     */
    public String getErrorCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>preprod.error.reason</code>.
     */
    public void setReason(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>preprod.error.reason</code>.
     */
    public String getReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>preprod.error.details</code>.
     */
    public void setDetails(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>preprod.error.details</code>.
     */
    public String getDetails() {
        return (String) get(4);
    }

    /**
     * Setter for <code>preprod.error.update_datetime</code>.
     */
    public void setUpdateDatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>preprod.error.update_datetime</code>.
     */
    public LocalDateTime getUpdateDatetime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ErrorRecord
     */
    public ErrorRecord() {
        super(Error.ERROR);
    }

    /**
     * Create a detached, initialised ErrorRecord
     */
    public ErrorRecord(Integer id, Long block, String errorCode, String reason, String details, LocalDateTime updateDatetime) {
        super(Error.ERROR);

        setId(id);
        setBlock(block);
        setErrorCode(errorCode);
        setReason(reason);
        setDetails(details);
        setUpdateDatetime(updateDatetime);
        resetChangedOnNotNull();
    }
}
