/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import java.time.LocalDateTime;

import org.cardanofoundation.rosetta.api.jooq.tables.ProtocolParamsProposal;
import org.jooq.JSONB;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProtocolParamsProposalRecord extends UpdatableRecordImpl<ProtocolParamsProposalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.protocol_params_proposal.tx_hash</code>.
     */
    public void setTxHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.tx_hash</code>.
     */
    public String getTxHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.key_hash</code>.
     */
    public void setKeyHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.key_hash</code>.
     */
    public String getKeyHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.params</code>.
     */
    public void setParams(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.params</code>.
     */
    public JSONB getParams() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.target_epoch</code>.
     */
    public void setTargetEpoch(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.target_epoch</code>.
     */
    public Integer getTargetEpoch() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.epoch</code>.
     */
    public void setEpoch(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.epoch</code>.
     */
    public Integer getEpoch() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.slot</code>.
     */
    public void setSlot(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.slot</code>.
     */
    public Long getSlot() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.era</code>.
     */
    public void setEra(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.era</code>.
     */
    public Short getEra() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.block</code>.
     */
    public void setBlock(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.block</code>.
     */
    public Long getBlock() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.block_time</code>.
     */
    public void setBlockTime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.block_time</code>.
     */
    public Long getBlockTime() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.protocol_params_proposal.update_datetime</code>.
     */
    public void setUpdateDatetime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.protocol_params_proposal.update_datetime</code>.
     */
    public LocalDateTime getUpdateDatetime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProtocolParamsProposalRecord
     */
    public ProtocolParamsProposalRecord() {
        super(ProtocolParamsProposal.PROTOCOL_PARAMS_PROPOSAL);
    }

    /**
     * Create a detached, initialised ProtocolParamsProposalRecord
     */
    public ProtocolParamsProposalRecord(String txHash, String keyHash, JSONB params, Integer targetEpoch, Integer epoch, Long slot, Short era, Long block, Long blockTime, LocalDateTime updateDatetime) {
        super(ProtocolParamsProposal.PROTOCOL_PARAMS_PROPOSAL);

        setTxHash(txHash);
        setKeyHash(keyHash);
        setParams(params);
        setTargetEpoch(targetEpoch);
        setEpoch(epoch);
        setSlot(slot);
        setEra(era);
        setBlock(block);
        setBlockTime(blockTime);
        setUpdateDatetime(updateDatetime);
        resetChangedOnNotNull();
    }
}
