/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import org.cardanofoundation.rosetta.api.jooq.tables.TransactionSize;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionSizeRecord extends UpdatableRecordImpl<TransactionSizeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.transaction_size.tx_hash</code>.
     */
    public void setTxHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.transaction_size.tx_hash</code>.
     */
    public String getTxHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.transaction_size.block_number</code>.
     */
    public void setBlockNumber(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.transaction_size.block_number</code>.
     */
    public Long getBlockNumber() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.transaction_size.size</code>.
     */
    public void setSize(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.transaction_size.size</code>.
     */
    public Integer getSize() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.transaction_size.script_size</code>.
     */
    public void setScriptSize(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.transaction_size.script_size</code>.
     */
    public Integer getScriptSize() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionSizeRecord
     */
    public TransactionSizeRecord() {
        super(TransactionSize.TRANSACTION_SIZE);
    }

    /**
     * Create a detached, initialised TransactionSizeRecord
     */
    public TransactionSizeRecord(String txHash, Long blockNumber, Integer size, Integer scriptSize) {
        super(TransactionSize.TRANSACTION_SIZE);

        setTxHash(txHash);
        setBlockNumber(blockNumber);
        setSize(size);
        setScriptSize(scriptSize);
        resetChangedOnNotNull();
    }
}
