/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables.records;


import java.math.BigInteger;
import java.time.LocalDateTime;

import org.cardanofoundation.rosetta.api.jooq.tables.Withdrawal;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WithdrawalRecord extends UpdatableRecordImpl<WithdrawalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.withdrawal.tx_hash</code>.
     */
    public void setTxHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.withdrawal.tx_hash</code>.
     */
    public String getTxHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.withdrawal.address</code>.
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.withdrawal.address</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.withdrawal.amount</code>.
     */
    public void setAmount(BigInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.withdrawal.amount</code>.
     */
    public BigInteger getAmount() {
        return (BigInteger) get(2);
    }

    /**
     * Setter for <code>public.withdrawal.epoch</code>.
     */
    public void setEpoch(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.withdrawal.epoch</code>.
     */
    public Integer getEpoch() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.withdrawal.slot</code>.
     */
    public void setSlot(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.withdrawal.slot</code>.
     */
    public Long getSlot() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.withdrawal.block</code>.
     */
    public void setBlock(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.withdrawal.block</code>.
     */
    public Long getBlock() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.withdrawal.block_time</code>.
     */
    public void setBlockTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.withdrawal.block_time</code>.
     */
    public Long getBlockTime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.withdrawal.update_datetime</code>.
     */
    public void setUpdateDatetime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.withdrawal.update_datetime</code>.
     */
    public LocalDateTime getUpdateDatetime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WithdrawalRecord
     */
    public WithdrawalRecord() {
        super(Withdrawal.WITHDRAWAL);
    }

    /**
     * Create a detached, initialised WithdrawalRecord
     */
    public WithdrawalRecord(String txHash, String address, BigInteger amount, Integer epoch, Long slot, Long block, Long blockTime, LocalDateTime updateDatetime) {
        super(Withdrawal.WITHDRAWAL);

        setTxHash(txHash);
        setAddress(address);
        setAmount(amount);
        setEpoch(epoch);
        setSlot(slot);
        setBlock(block);
        setBlockTime(blockTime);
        setUpdateDatetime(updateDatetime);
        resetChangedOnNotNull();
    }
}
