version: '3.8'
services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
    volumes:
      - ${CARDANO_NODE_SOCKET_PATH}:${CARDANO_NODE_SOCKET_PATH}
      - ${CARDANO_NODE_DB}:/data/db
      - ${CARDANO_CONFIG}:/config
    ports:
      - ${CARDANO_NODE_PORT}:${CARDANO_NODE_PORT}
    entrypoint: cardano-node run --database-path /data/db --port ${CARDANO_NODE_PORT} --socket-path ${CARDANO_NODE_SOCKET} --topology /config/topology.json --config /config/config.json

  cardano-submit-api:
    image: ghcr.io/intersectmbo/cardano-submit-api:${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
    depends_on:
      - cardano-node
    volumes:
      - ${CARDANO_NODE_SOCKET_PATH}:/node-ipc
    ports:
      - ${NODE_SUBMIT_API_PORT}:8090
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    name: cardano-rosetta-java-${NETWORK}
