version: '3.8'
services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
    volumes:
      - ${CARDANO_NODE_SOCKET_PATH}:/ipc
      - ${CARDANO_NODE_DB}:/data/db
      - ${CARDANO_CONFIG}:/current
    ports:
      - ${CARDANO_NODE_PORT}:${CARDANO_NODE_PORT}
    entrypoint: cardano-node run --port ${CARDANO_NODE_PORT} --config /current/config.json --topology /current/topology.json --database-path /data/db --socket-path /ipc/node.socket

  cardano-submit-api:
    image: ghcr.io/intersectmbo/cardano-submit-api:${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
    depends_on:
      - cardano-node
    volumes:
      - ${CARDANO_NODE_SOCKET_PATH}:/node-ipc
    ports:
      - ${NODE_SUBMIT_API_PORT}:8090
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    name: cardano-rosetta-java-${NETWORK}
