version: '3.8'
services:
  mithril:
    image: cardanofoundation/cardano-rosetta-java-mithril:${MITHRIL_VERSION}
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/mithril/Dockerfile
      args: 
        MITHRIL_VERSION: ${MITHRIL_VERSION}
    environment:
      - NETWORK=${NETWORK}
      - MITHRIL_SYNC=${MITHRIL_SYNC}
      - SNAPSHOT_DIGEST=${SNAPSHOT_DIGEST}
      - AGGREGATOR_ENDPOINT=${AGGREGATOR_ENDPOINT}
      - GENESIS_VERIFICATION_KEY=${GENESIS_VERIFICATION_KEY}
      - ANCILLARY_VERIFICATION_KEY=${ANCILLARY_VERIFICATION_KEY}
    volumes:
      - ${CARDANO_NODE_DIR}:/node

  cardano-node:
    image: cardanofoundation/cardano-rosetta-java-cardano-node:${CARDANO_NODE_VERSION}
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/node/Dockerfile
      args:
        CARDANO_NODE_VERSION: ${CARDANO_NODE_VERSION}
    environment:
      - CARDANO_NODE_SOCKET_PATH=${CARDANO_NODE_SOCKET_PATH}
      - CARDANO_NODE_PORT=${CARDANO_NODE_PORT}
      - CARDANO_NODE_DB=${CARDANO_NODE_DB}
    volumes:
      - ${CARDANO_NODE_DIR}:${CARDANO_NODE_DIR}
      - ${CARDANO_NODE_DB}:${CARDANO_NODE_DB}
      - ${CARDANO_CONFIG}:/config
    restart: unless-stopped
    ports:
      - ${CARDANO_NODE_PORT}:${CARDANO_NODE_PORT}
    entrypoint: ["/sbin/entrypoint.sh", "cardano-node"]
    depends_on:
      mithril:
        condition: service_completed_successfully

  cardano-submit-api:
    image: cardanofoundation/cardano-rosetta-java-cardano-node:${CARDANO_NODE_VERSION}
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/node/Dockerfile
      args:
        CARDANO_NODE_VERSION: ${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
      - PROTOCOL_MAGIC=${PROTOCOL_MAGIC}
      - CARDANO_NODE_SOCKET_PATH=${CARDANO_NODE_SOCKET_PATH}
      - NODE_SUBMIT_API_PORT=${NODE_SUBMIT_API_PORT}
    volumes:
      - ${CARDANO_NODE_DIR}:${CARDANO_NODE_DIR}
      - ${CARDANO_CONFIG}:/config
    restart: unless-stopped
    ports:
      - ${NODE_SUBMIT_API_PORT}:${NODE_SUBMIT_API_PORT}
    entrypoint: ["/sbin/entrypoint.sh", "cardano-submit-api"]
    depends_on:
      mithril:
        condition: service_completed_successfully

  cardano-sync-waiter:
    image: cardanofoundation/cardano-rosetta-java-cardano-node:${CARDANO_NODE_VERSION}
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/node/Dockerfile
      args:
        CARDANO_NODE_VERSION: ${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
      - PROTOCOL_MAGIC=${PROTOCOL_MAGIC}
      - CARDANO_NODE_SOCKET_PATH=${CARDANO_NODE_SOCKET_PATH}
      - GENESIS_SHELLEY_PATH=${GENESIS_SHELLEY_PATH}
      - GENESIS_BYRON_PATH=${GENESIS_BYRON_PATH}
      - SYNC=${SYNC}
    volumes:
      - ${CARDANO_NODE_DIR}:${CARDANO_NODE_DIR}
      - ${CARDANO_CONFIG}:/config
    restart: no
    entrypoint: ["/sbin/wait-for-node-sync.sh"]
    depends_on:
      cardano-node:
        condition: service_started

networks:
  default:
    name: cardano-rosetta-java-${NETWORK}
