{{- if (index .Values.global "pgExporter" (dict)).enabled | default false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-pg-exporter" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.commonLabels" . | nindent 4 }}
    component: pg-exporter
spec:
  type: ClusterIP
  selector:
    app: {{ printf "%s-pg-exporter" .Release.Name }}
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
{{- end }}
