{{- if not .Values.global.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cardano-rosetta-java.dbSecretName" . }}
  labels:
    {{- include "postgresql.commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  db-secret: {{ required "global.db.password is required. Set it with --set global.db.password=<value>" .Values.global.db.password | quote }}
{{- end }}
