FROM eclipse-temurin:21-jdk

WORKDIR /

ARG PG_VERSION=11

# Postgres
RUN apt-get update --fix-missing \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y wget sudo gnupg \
    && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && echo 'deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main' >> /etc/apt/sources.list

RUN apt-get update --fix-missing \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    postgresql-${PG_VERSION}

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/$PG_VERSION/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/$PG_VERSION/main/postgresql.conf

# Node
COPY ./docker/node /usr/local/lib
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
ENV PATH="/usr/local/lib/:$PATH"

RUN cd /usr/local/lib/ \
    && chmod -R -f 755 * \
    && ln -s libsecp256k1.so.2.0.2 libsecp256k1.so.2 \
    && ln -s libsecp256k1.so.2.0.2 libsecp256k1.so \
    && ln -s libsodium.so.23.3.0 libsodium.so.23 \
    && ln -s libsodium.so.23.3.0 libsodium.so

COPY ./config /config_bck
RUN mkdir /config

RUN mkdir -p /data/db
RUN mkdir /ipc

# Java
COPY ./api/target/*.jar /api/app.jar
COPY ./yaci-indexer/target/*.jar /yaci-indexer/app.jar

# Run
RUN mkdir /logs

EXPOSE 8081
#EXPOSE 8081 5432 3001 12788 12798

COPY ./docker/entrypoint.sh /sbin/entrypoint.sh
ENTRYPOINT ["/sbin/entrypoint.sh"]

CMD ["/bin/sh", "-c", "bash"]
