{
 "title": "Rosetta Critical Operation Metrics",
 "description": "Rosetta-java monitoring",
 "tags": [
  "node",
  "postgres",
  "indexer",
  "api"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Api Container Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"api\"}"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"api\"})"
    }
   ]
  },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_max{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_idle{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{application=\"api\", pool=\"CardanoRosettaJavaDBPool\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"api\", pool=\"CardanoRosettaJavaDBPool\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"api\", pool=\"CardanoRosettaJavaDBPool\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"api\", pool=\"CardanoRosettaJavaDBPool\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "HikariCP Connections Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_usage_seconds_sum{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}[5m]) / irate(hikaricp_connections_usage_seconds_count{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}[5m])",
     "legendFormat": "Usage time"
    },
    {
     "expr": "irate(hikaricp_connections_creation_seconds_sum{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}[5m]) / \r\nirate(hikaricp_connections_creation_seconds_count{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}[5m])",
     "legendFormat": "Creation time"
    },
    {
     "expr": "irate(hikaricp_connections_acquire_seconds_sum{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}[5m]) / irate(hikaricp_connections_acquire_seconds_count{application=\"api\",pool=\"CardanoRosettaJavaDBPool\"}[5m])",
     "legendFormat": "Acquire time"
    }
   ]
  },
  {
   "title": "Yaci-Indexer Container Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"yaci_indexer\"}"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"yaci_indexer\"})"
    }
   ]
  },
  {
   "title": "Connections Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_max{application=\"yaci_indexer\", pool=\"HikariPool-1\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"yaci_indexer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_min{application=\"yaci_indexer\", pool=\"HikariPool-1\"}"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{application=\"yaci_indexer\", pool=\"HikariPool-1\"}"
    }
   ]
  },
  {
   "title": "HikariCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"yaci_indexer\", pool=\"HikariPool-1\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"yaci_indexer\", pool=\"HikariPool-1\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"yaci_indexer\", pool=\"HikariPool-1\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "HikariCP Connections Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_usage_seconds_sum{application=\"yaci_indexer\",pool=\"HikariPool-1\"}[5m]) / irate(hikaricp_connections_usage_seconds_count{application=\"yaci_indexer\",pool=\"HikariPool-1\"}[5m])",
     "legendFormat": "Usage time"
    },
    {
     "expr": "irate(hikaricp_connections_creation_seconds_sum{application=\"yaci_indexer\",pool=\"HikariPool-1\"}[5m]) / \r\nirate(hikaricp_connections_creation_seconds_count{application=\"yaci_indexer\",pool=\"HikariPool-1\"}[5m])",
     "legendFormat": "Creation time"
    },
    {
     "expr": "irate(hikaricp_connections_acquire_seconds_sum{application=\"yaci_indexer\"}[5m]) / irate(hikaricp_connections_acquire_seconds_count{application=\"yaci_indexer\"}[5m])",
     "legendFormat": "Acquire time"
    }
   ]
  },
  { "title": "Postgres Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "postgreSQL Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{application=\"postgreSQL_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "deadlocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_deadlocks{application=\"postgreSQL_exporter\",datname=\"rosetta-java\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max_connects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{application=\"postgreSQL_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "current_connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "io_concurency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_io_concurrency{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "shared_buffer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "database_size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{application=\"postgreSQL_exporter\",datname=\"rosetta-java\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max_parallel_worker",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "effective_cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max_wal_size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "maintenance_work_mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "work_mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pg_settings_work_mem_bytes{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "active_sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{application=\"postgreSQL_exporter\",datname=\"rosetta-java\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cardano node Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{application=\"cardano_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Mem_resident_int{application=\"cardano_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incomming peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_incomingConns"
    }
   ]
  },
  {
   "title": "Outgoing peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_outgoingConns"
    }
   ]
  },
  {
   "title": "Epoch No",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{application=\"cardano_node\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{application=\"cardano_node\"}"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{application=\"cardano_node\"}"
    }
   ]
  },
  {
   "title": "Block Density",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{application=\"cardano_node\"}*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{application=\"cardano_node\"}*10/43200"
    }
   ]
  },
  {
   "title": "% Block Propagation <1s",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfOne{application=\"cardano_node\"}*100"
    }
   ]
  },
  {
   "title": "% Block Propagation <3s",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfThree{application=\"cardano_node\"}*100"
    }
   ]
  },
  {
   "title": "% Block Propagation <5s",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfFive{application=\"cardano_node\"}*100"
    }
   ]
  }
 ]
}