apiVersion: v1
kind: Service
metadata:
  name: {{ include "rosetta-api.fullname" . }}
  labels:
    {{- include "rosetta-api.commonLabels" . | nindent 4 }}
    component: rosetta-api
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "rosetta-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
