/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import org.cardanofoundation.rosetta.api.jooq.Keys;
import org.cardanofoundation.rosetta.api.jooq.Public;
import org.cardanofoundation.rosetta.api.jooq.tables.records.LocalEpochParamRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LocalEpochParam extends TableImpl<LocalEpochParamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.local_epoch_param</code>
     */
    public static final LocalEpochParam LOCAL_EPOCH_PARAM = new LocalEpochParam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LocalEpochParamRecord> getRecordType() {
        return LocalEpochParamRecord.class;
    }

    /**
     * The column <code>public.local_epoch_param.epoch</code>.
     */
    public final TableField<LocalEpochParamRecord, Integer> EPOCH = createField(DSL.name("epoch"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.local_epoch_param.params</code>.
     */
    public final TableField<LocalEpochParamRecord, JSONB> PARAMS = createField(DSL.name("params"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.local_epoch_param.update_datetime</code>.
     */
    public final TableField<LocalEpochParamRecord, LocalDateTime> UPDATE_DATETIME = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    private LocalEpochParam(Name alias, Table<LocalEpochParamRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LocalEpochParam(Name alias, Table<LocalEpochParamRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.local_epoch_param</code> table reference
     */
    public LocalEpochParam(String alias) {
        this(DSL.name(alias), LOCAL_EPOCH_PARAM);
    }

    /**
     * Create an aliased <code>public.local_epoch_param</code> table reference
     */
    public LocalEpochParam(Name alias) {
        this(alias, LOCAL_EPOCH_PARAM);
    }

    /**
     * Create a <code>public.local_epoch_param</code> table reference
     */
    public LocalEpochParam() {
        this(DSL.name("local_epoch_param"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LocalEpochParamRecord> getPrimaryKey() {
        return Keys.LOCAL_EPOCH_PARAM_PKEY;
    }

    @Override
    public LocalEpochParam as(String alias) {
        return new LocalEpochParam(DSL.name(alias), this);
    }

    @Override
    public LocalEpochParam as(Name alias) {
        return new LocalEpochParam(alias, this);
    }

    @Override
    public LocalEpochParam as(Table<?> alias) {
        return new LocalEpochParam(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LocalEpochParam rename(String name) {
        return new LocalEpochParam(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LocalEpochParam rename(Name name) {
        return new LocalEpochParam(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LocalEpochParam rename(Table<?> name) {
        return new LocalEpochParam(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LocalEpochParam where(Condition condition) {
        return new LocalEpochParam(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LocalEpochParam where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LocalEpochParam where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LocalEpochParam where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LocalEpochParam where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LocalEpochParam where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LocalEpochParam where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LocalEpochParam where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LocalEpochParam whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LocalEpochParam whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
