/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.cardanofoundation.rosetta.api.jooq.Indexes;
import org.cardanofoundation.rosetta.api.jooq.Keys;
import org.cardanofoundation.rosetta.api.jooq.Public;
import org.cardanofoundation.rosetta.api.jooq.tables.records.PoolRetirementRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PoolRetirement extends TableImpl<PoolRetirementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pool_retirement</code>
     */
    public static final PoolRetirement POOL_RETIREMENT = new PoolRetirement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PoolRetirementRecord> getRecordType() {
        return PoolRetirementRecord.class;
    }

    /**
     * The column <code>public.pool_retirement.tx_hash</code>.
     */
    public final TableField<PoolRetirementRecord, String> TX_HASH = createField(DSL.name("tx_hash"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.pool_retirement.cert_index</code>.
     */
    public final TableField<PoolRetirementRecord, Integer> CERT_INDEX = createField(DSL.name("cert_index"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.pool_retirement.pool_id</code>.
     */
    public final TableField<PoolRetirementRecord, String> POOL_ID = createField(DSL.name("pool_id"), SQLDataType.VARCHAR(56), this, "");

    /**
     * The column <code>public.pool_retirement.retirement_epoch</code>.
     */
    public final TableField<PoolRetirementRecord, Integer> RETIREMENT_EPOCH = createField(DSL.name("retirement_epoch"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.pool_retirement.epoch</code>.
     */
    public final TableField<PoolRetirementRecord, Integer> EPOCH = createField(DSL.name("epoch"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.pool_retirement.slot</code>.
     */
    public final TableField<PoolRetirementRecord, Long> SLOT = createField(DSL.name("slot"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pool_retirement.block_hash</code>.
     */
    public final TableField<PoolRetirementRecord, String> BLOCK_HASH = createField(DSL.name("block_hash"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.pool_retirement.block</code>.
     */
    public final TableField<PoolRetirementRecord, Long> BLOCK = createField(DSL.name("block"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pool_retirement.block_time</code>.
     */
    public final TableField<PoolRetirementRecord, Long> BLOCK_TIME = createField(DSL.name("block_time"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pool_retirement.update_datetime</code>.
     */
    public final TableField<PoolRetirementRecord, LocalDateTime> UPDATE_DATETIME = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    private PoolRetirement(Name alias, Table<PoolRetirementRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PoolRetirement(Name alias, Table<PoolRetirementRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pool_retirement</code> table reference
     */
    public PoolRetirement(String alias) {
        this(DSL.name(alias), POOL_RETIREMENT);
    }

    /**
     * Create an aliased <code>public.pool_retirement</code> table reference
     */
    public PoolRetirement(Name alias) {
        this(alias, POOL_RETIREMENT);
    }

    /**
     * Create a <code>public.pool_retirement</code> table reference
     */
    public PoolRetirement() {
        this(DSL.name("pool_retirement"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_POOL_RETIREMENT_POOL_ID, Indexes.IDX_POOL_RETIREMENT_RETIREMENT_EPOCH, Indexes.IDX_POOL_RETIREMENT_SLOT, Indexes.IDX_POOL_RETIREMENT_TXHASH);
    }

    @Override
    public UniqueKey<PoolRetirementRecord> getPrimaryKey() {
        return Keys.POOL_RETIREMENT_PKEY;
    }

    @Override
    public PoolRetirement as(String alias) {
        return new PoolRetirement(DSL.name(alias), this);
    }

    @Override
    public PoolRetirement as(Name alias) {
        return new PoolRetirement(alias, this);
    }

    @Override
    public PoolRetirement as(Table<?> alias) {
        return new PoolRetirement(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PoolRetirement rename(String name) {
        return new PoolRetirement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PoolRetirement rename(Name name) {
        return new PoolRetirement(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PoolRetirement rename(Table<?> name) {
        return new PoolRetirement(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoolRetirement where(Condition condition) {
        return new PoolRetirement(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoolRetirement where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoolRetirement where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoolRetirement where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PoolRetirement where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PoolRetirement where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PoolRetirement where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PoolRetirement where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoolRetirement whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoolRetirement whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
