/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.cardanofoundation.rosetta.api.jooq.Indexes;
import org.cardanofoundation.rosetta.api.jooq.Keys;
import org.cardanofoundation.rosetta.api.jooq.Public;
import org.cardanofoundation.rosetta.api.jooq.tables.records.ProtocolParamsProposalRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProtocolParamsProposal extends TableImpl<ProtocolParamsProposalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.protocol_params_proposal</code>
     */
    public static final ProtocolParamsProposal PROTOCOL_PARAMS_PROPOSAL = new ProtocolParamsProposal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProtocolParamsProposalRecord> getRecordType() {
        return ProtocolParamsProposalRecord.class;
    }

    /**
     * The column <code>public.protocol_params_proposal.tx_hash</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, String> TX_HASH = createField(DSL.name("tx_hash"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.protocol_params_proposal.key_hash</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, String> KEY_HASH = createField(DSL.name("key_hash"), SQLDataType.VARCHAR(56).nullable(false), this, "");

    /**
     * The column <code>public.protocol_params_proposal.params</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, JSONB> PARAMS = createField(DSL.name("params"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.protocol_params_proposal.target_epoch</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, Integer> TARGET_EPOCH = createField(DSL.name("target_epoch"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.protocol_params_proposal.epoch</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, Integer> EPOCH = createField(DSL.name("epoch"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.protocol_params_proposal.slot</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, Long> SLOT = createField(DSL.name("slot"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.protocol_params_proposal.era</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, Short> ERA = createField(DSL.name("era"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.protocol_params_proposal.block</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, Long> BLOCK = createField(DSL.name("block"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.protocol_params_proposal.block_time</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, Long> BLOCK_TIME = createField(DSL.name("block_time"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.protocol_params_proposal.update_datetime</code>.
     */
    public final TableField<ProtocolParamsProposalRecord, LocalDateTime> UPDATE_DATETIME = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    private ProtocolParamsProposal(Name alias, Table<ProtocolParamsProposalRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProtocolParamsProposal(Name alias, Table<ProtocolParamsProposalRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.protocol_params_proposal</code> table
     * reference
     */
    public ProtocolParamsProposal(String alias) {
        this(DSL.name(alias), PROTOCOL_PARAMS_PROPOSAL);
    }

    /**
     * Create an aliased <code>public.protocol_params_proposal</code> table
     * reference
     */
    public ProtocolParamsProposal(Name alias) {
        this(alias, PROTOCOL_PARAMS_PROPOSAL);
    }

    /**
     * Create a <code>public.protocol_params_proposal</code> table reference
     */
    public ProtocolParamsProposal() {
        this(DSL.name("protocol_params_proposal"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PROTOCOL_PARAMS_PROPOSAL_EPOCH, Indexes.IDX_PROTOCOL_PARAMS_PROPOSAL_SLOT, Indexes.IDX_PROTOCOL_PARAMS_PROPOSAL_TARGET_EPOCH);
    }

    @Override
    public UniqueKey<ProtocolParamsProposalRecord> getPrimaryKey() {
        return Keys.PROTOCOL_PARAMS_PROPOSAL_PKEY;
    }

    @Override
    public ProtocolParamsProposal as(String alias) {
        return new ProtocolParamsProposal(DSL.name(alias), this);
    }

    @Override
    public ProtocolParamsProposal as(Name alias) {
        return new ProtocolParamsProposal(alias, this);
    }

    @Override
    public ProtocolParamsProposal as(Table<?> alias) {
        return new ProtocolParamsProposal(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProtocolParamsProposal rename(String name) {
        return new ProtocolParamsProposal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProtocolParamsProposal rename(Name name) {
        return new ProtocolParamsProposal(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProtocolParamsProposal rename(Table<?> name) {
        return new ProtocolParamsProposal(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProtocolParamsProposal where(Condition condition) {
        return new ProtocolParamsProposal(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProtocolParamsProposal where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProtocolParamsProposal where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProtocolParamsProposal where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProtocolParamsProposal where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProtocolParamsProposal where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProtocolParamsProposal where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProtocolParamsProposal where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProtocolParamsProposal whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProtocolParamsProposal whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
