/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.cardanofoundation.rosetta.api.jooq.Indexes;
import org.cardanofoundation.rosetta.api.jooq.Keys;
import org.cardanofoundation.rosetta.api.jooq.Preprod;
import org.cardanofoundation.rosetta.api.jooq.tables.records.StakeRegistrationRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StakeRegistration extends TableImpl<StakeRegistrationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>preprod.stake_registration</code>
     */
    public static final StakeRegistration STAKE_REGISTRATION = new StakeRegistration();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StakeRegistrationRecord> getRecordType() {
        return StakeRegistrationRecord.class;
    }

    /**
     * The column <code>preprod.stake_registration.tx_hash</code>.
     */
    public final TableField<StakeRegistrationRecord, String> TX_HASH = createField(DSL.name("tx_hash"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>preprod.stake_registration.cert_index</code>.
     */
    public final TableField<StakeRegistrationRecord, Integer> CERT_INDEX = createField(DSL.name("cert_index"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>preprod.stake_registration.credential</code>.
     */
    public final TableField<StakeRegistrationRecord, String> CREDENTIAL = createField(DSL.name("credential"), SQLDataType.VARCHAR(56).nullable(false), this, "");

    /**
     * The column <code>preprod.stake_registration.type</code>.
     */
    public final TableField<StakeRegistrationRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>preprod.stake_registration.address</code>.
     */
    public final TableField<StakeRegistrationRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>preprod.stake_registration.epoch</code>.
     */
    public final TableField<StakeRegistrationRecord, Integer> EPOCH = createField(DSL.name("epoch"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>preprod.stake_registration.slot</code>.
     */
    public final TableField<StakeRegistrationRecord, Long> SLOT = createField(DSL.name("slot"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>preprod.stake_registration.block_hash</code>.
     */
    public final TableField<StakeRegistrationRecord, String> BLOCK_HASH = createField(DSL.name("block_hash"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>preprod.stake_registration.block</code>.
     */
    public final TableField<StakeRegistrationRecord, Long> BLOCK = createField(DSL.name("block"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>preprod.stake_registration.block_time</code>.
     */
    public final TableField<StakeRegistrationRecord, Long> BLOCK_TIME = createField(DSL.name("block_time"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>preprod.stake_registration.update_datetime</code>.
     */
    public final TableField<StakeRegistrationRecord, LocalDateTime> UPDATE_DATETIME = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    private StakeRegistration(Name alias, Table<StakeRegistrationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StakeRegistration(Name alias, Table<StakeRegistrationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>preprod.stake_registration</code> table reference
     */
    public StakeRegistration(String alias) {
        this(DSL.name(alias), STAKE_REGISTRATION);
    }

    /**
     * Create an aliased <code>preprod.stake_registration</code> table reference
     */
    public StakeRegistration(Name alias) {
        this(alias, STAKE_REGISTRATION);
    }

    /**
     * Create a <code>preprod.stake_registration</code> table reference
     */
    public StakeRegistration() {
        this(DSL.name("stake_registration"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Preprod.PREPROD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_STAKE_REGISTRATION_SLOT, Indexes.IDX_STAKE_REGISTRATION_STAKE_ADDRESS, Indexes.IDX_STAKE_REGISTRATION_STAKE_CREDENTIAL, Indexes.IDX_STAKE_REGISTRATION_STAKE_TXHASH, Indexes.IDX_STAKE_REGISTRATION_TYPE);
    }

    @Override
    public UniqueKey<StakeRegistrationRecord> getPrimaryKey() {
        return Keys.STAKE_REGISTRATION_PKEY;
    }

    @Override
    public StakeRegistration as(String alias) {
        return new StakeRegistration(DSL.name(alias), this);
    }

    @Override
    public StakeRegistration as(Name alias) {
        return new StakeRegistration(alias, this);
    }

    @Override
    public StakeRegistration as(Table<?> alias) {
        return new StakeRegistration(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StakeRegistration rename(String name) {
        return new StakeRegistration(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StakeRegistration rename(Name name) {
        return new StakeRegistration(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StakeRegistration rename(Table<?> name) {
        return new StakeRegistration(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StakeRegistration where(Condition condition) {
        return new StakeRegistration(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StakeRegistration where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StakeRegistration where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StakeRegistration where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StakeRegistration where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StakeRegistration where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StakeRegistration where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StakeRegistration where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StakeRegistration whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StakeRegistration whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
