/*
 * This file is generated by jOOQ.
 */
package org.cardanofoundation.rosetta.api.jooq.tables;


import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.cardanofoundation.rosetta.api.jooq.Indexes;
import org.cardanofoundation.rosetta.api.jooq.Keys;
import org.cardanofoundation.rosetta.api.jooq.Preprod;
import org.cardanofoundation.rosetta.api.jooq.tables.records.WithdrawalRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Withdrawal extends TableImpl<WithdrawalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.withdrawal</code>
     */
    public static final Withdrawal WITHDRAWAL = new Withdrawal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithdrawalRecord> getRecordType() {
        return WithdrawalRecord.class;
    }

    /**
     * The column <code>public.withdrawal.tx_hash</code>.
     */
    public final TableField<WithdrawalRecord, String> TX_HASH = createField(DSL.name("tx_hash"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.withdrawal.address</code>.
     */
    public final TableField<WithdrawalRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.withdrawal.amount</code>.
     */
    public final TableField<WithdrawalRecord, BigInteger> AMOUNT = createField(DSL.name("amount"), SQLDataType.DECIMAL_INTEGER(38), this, "");

    /**
     * The column <code>public.withdrawal.epoch</code>.
     */
    public final TableField<WithdrawalRecord, Integer> EPOCH = createField(DSL.name("epoch"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.withdrawal.slot</code>.
     */
    public final TableField<WithdrawalRecord, Long> SLOT = createField(DSL.name("slot"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.withdrawal.block</code>.
     */
    public final TableField<WithdrawalRecord, Long> BLOCK = createField(DSL.name("block"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.withdrawal.block_time</code>.
     */
    public final TableField<WithdrawalRecord, Long> BLOCK_TIME = createField(DSL.name("block_time"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.withdrawal.update_datetime</code>.
     */
    public final TableField<WithdrawalRecord, LocalDateTime> UPDATE_DATETIME = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    private Withdrawal(Name alias, Table<WithdrawalRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Withdrawal(Name alias, Table<WithdrawalRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.withdrawal</code> table reference
     */
    public Withdrawal(String alias) {
        this(DSL.name(alias), WITHDRAWAL);
    }

    /**
     * Create an aliased <code>public.withdrawal</code> table reference
     */
    public Withdrawal(Name alias) {
        this(alias, WITHDRAWAL);
    }

    /**
     * Create a <code>public.withdrawal</code> table reference
     */
    public Withdrawal() {
        this(DSL.name("withdrawal"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Preprod.PREPROD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_WITHDRAWAL_ADDRESS, Indexes.IDX_WITHDRAWAL_SLOT, Indexes.IDX_WITHDRAWAL_TX_HASH);
    }

    @Override
    public UniqueKey<WithdrawalRecord> getPrimaryKey() {
        return Keys.WITHDRAWAL_PKEY;
    }

    @Override
    public Withdrawal as(String alias) {
        return new Withdrawal(DSL.name(alias), this);
    }

    @Override
    public Withdrawal as(Name alias) {
        return new Withdrawal(alias, this);
    }

    @Override
    public Withdrawal as(Table<?> alias) {
        return new Withdrawal(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Withdrawal rename(String name) {
        return new Withdrawal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Withdrawal rename(Name name) {
        return new Withdrawal(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Withdrawal rename(Table<?> name) {
        return new Withdrawal(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Withdrawal where(Condition condition) {
        return new Withdrawal(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Withdrawal where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Withdrawal where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Withdrawal where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Withdrawal where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Withdrawal where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Withdrawal where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Withdrawal where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Withdrawal whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Withdrawal whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
