apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cardano-rosetta-java.rolebindingName" . }}
  labels:
    {{- include "cardano-rosetta-java.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cardano-rosetta-java.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cardano-rosetta-java.saName" . }}
    namespace: {{ .Release.Namespace }}
