name: Deploy Docs to GitHub Pages

on:
  # Trigger on pushes to main branch
  push:
    branches: [main]
    paths:
      - "docs/**"
  # Allow manual triggering
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy OpenAPI spec
        run: mkdir -p docs/static && cp api/src/main/resources/rosetta-specifications-1.4.15/api.yaml docs/static/api.yaml
        working-directory: ${{ github.workspace }} # Run from root

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          # User que fez o commit ao gh-pages branch
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
