name: Fossa Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Download and Install FOSSA CLI"
        shell: bash
        run: |
          wget https://github.com/fossas/fossa-cli/releases/download/v3.10.6/fossa_3.10.6_linux_amd64.zip
          unzip fossa_3.10.6_linux_amd64.zip
          chmod +x fossa
          mv fossa fossa-cli

      - name: "Run FOSSA Test with Config"
        shell: bash
        run: |
          ./fossa-cli test --config .fossa.yml --fossa-api-key ${{secrets.FOSSA_API_KEY}}

