name: Build pre-release

on:
  release:
    types:
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Free Diskspace
        uses: ./.github/actions/free_disk_space
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Cardano Rosetta Pre-Release
        uses: ./.github/actions/build_docker_images
        with:
          tag: ${{ github.event.release.tag_name }}-pre-release
