name: Build Docker images
description: Builds and pushes Docker images for the Cardano Rosetta project including API, Indexer and All-in-one Image
inputs:
  tag:
    description: Docker tag
    required: true
    default: main
  isRelease:
    description: Is this a release build? If true, the latest tag will be applied
    required: false
    default: false
secrets:
  DOCKERHUB_USERNAME:
    description: Docker Hub username
    required: true
    DOCKERHUB_TOKEN:
      description: Docker Hub token
      required: true
runs:
    using: composite
    steps:
      - name: API - Build and push Docker ${{ inputs.tag }} image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./api/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-api:${{ inputs.tag }}
          push: true
      - name: API - Build and push Docker latest image
        uses: docker/build-push-action@v4
        if: ${{ inputs.isRelease == 'true' }}
        with:
          context: .
          file: ./api/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-api:latest
          push: true
      - name: Indexer - Build and push Docker ${{ inputs.tag }} image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./yaci-indexer/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-indexer:${{ inputs.tag }}
          push: true
      - name: Indexer - Build and push Docker latest image
        uses: docker/build-push-action@v4
        if: ${{ inputs.isRelease == 'true' }}
        with:
          context: .
          file: ./yaci-indexer/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-indexer:latest
          push: true
      - name: Cardano Node - Build and push Docker ${{ inputs.tag }} image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dockerfiles/node/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-cardano-node:${{ inputs.tag }}
          push: true
      - name: Cardano Node - Build and push Docker latest image
        uses: docker/build-push-action@v4
        if: ${{ inputs.isRelease == 'true' }}
        with:
          context: .
          file: ./docker/dockerfiles/node/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-cardano-node:latest
          push: true
      - name: Postgres - Build and push Docker ${{ inputs.tag }} image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dockerfiles/postgres/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-postgres:${{ inputs.tag }}
          push: true
      - name: Postgres - Build and push Docker latest image
        uses: docker/build-push-action@v4
        if: ${{ inputs.isRelease == 'true' }}
        with:
          context: .
          file: ./docker/dockerfiles/postgres/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-postgres:latest
          push: true
      - name: Mithril - Build and push Docker ${{ inputs.tag }} image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dockerfiles/mithril/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-mithril:${{ inputs.tag }}
          push: true
      - name: Mithril - Build and push Docker latest image
        uses: docker/build-push-action@v4
        if: ${{ inputs.isRelease == 'true' }}
        with:
          context: .
          file: ./docker/dockerfiles/mithril/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java-mithril:latest
          push: true
      - name: All-in-one - Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java:${{ inputs.tag }}
          push: true
      - name: All-in-one - Build and push Docker latest image
        uses: docker/build-push-action@v4
        if: ${{ inputs.isRelease == 'true' }}
        with:
          context: .
          file: ./docker/Dockerfile
          tags: cardanofoundation/cardano-rosetta-java:latest
          push: true